# Generated by Django 4.0.6 on 2022-07-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationusers',
            options={'verbose_name': 'ApplicationUser', 'verbose_name_plural': 'ApplicationUsers'},
        ),
    ]
